name: Update palette cache
on: [push]
jobs:
  run-build-sh:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.6.1
      - name: Setup configuration directory
        run: |
          TARGET_DIR="$HOME/.config/nvim/pack/night-owl2.vim/start"
          mkdir --parents "$TARGET_DIR"
          cd "$TARGET_DIR"
          git clone 'https://github.com/ggzor/night-owl2.vim'
      - name: Run build.sh
        run: ./build.sh
      - name: Upload updated cache file
        uses: EndBug/add-and-commit@v9
        with:
          add: './autoload/nightowl2/palette.json'
          message: Update cache file
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com

